- app.js
- public/stylesheets/forget-pass.css
- routes/forget-pass.js
- views/forget-pass.hbs
> trang quen mk

- app.js
- public/stylesheets/login.css
- public/stylesheets/sign-up.css
- routes/login.js
- views/login.hbs
- views/sign-up.hbs
Branch mới đã cherry pick commit để khắc phục việc merge branch sign-up thì xóa nội dung branch log-in
> New sign up fix branch

- app.js
- public/stylesheets/style.css
- routes/categories.js
- views/categories.hbs
Thêm route trong app.js và sinh nội dung cứng các thể loại phổ biến.
> Hoàn thành trang thể loại

- app.js
- routes/about.js
- views/about.hbs
Chỉnh sửa app.js thêm trang giới thiệu khi route tới /about. 
Thêm 1 lớp first section với margin top lớn để thụt nội dung xuống hơn header.
> Hoàn thành trang giới thiệu

- app.js
- public/function/dropdown-search.js
- public/stylesheets/style.css
- routes/search.js
- views/search.hbs
Có thể tương tác dropdown đổi content
> Hoàn thành tạm trang tĩnh tìm kiếm

- app.js
- routes/cart-detail.js
- views/cart-detail.hbs
- Có responsive
- Thay đổi so với figma là button đưa vào center và comment đi dòng trở về giỏ sách. Nhìn đẹp hơn và dù nhấn btn nào thì cũng quay lại giỏ sách thôi nên không cần.
> Hoàn thành trang chi tiết sách

- app.js
- routes/rent-book-list.js
- routes/return-book-list.js
- views/rent-book-list.hbs
- views/return-book-list.hbs
- Responsive. 
- Chờ merge PR xong sẽ chỉnh thêm để tạo thêm trang hẹn mượn sách
> Hoàn thành trang hẹn trả sách

- app.js
- public/function/buy-book-menu.js
- public/stylesheets/buy-book-manager.css
- public/stylesheets/style.css
- routes/buy-book-manager.js
- views/buy-book-manager.hbs
toggle giữa đặt và mua
chưa có sort và search
> Trang quan ly mua sach

- views/carts.hbs
Trong phần giỏ sách có tính năng quay về trang trước nên cần thêm tính năng này.
> Bổ sung tính năng quay về trang trước

- public/function/layout.js
- public/template-html/giaovien-dropdown.html
- public/template-html/sinhvien-dropdown.html
- views/layout.hbs
- Cho phép đăng nhập thì cũng cho phép đăng xuất
- Trong lúc logout thì cũng remove account_type
> Xong phần logout

- app.js
- public/stylesheets/librarian-login.css
- routes/librarian-login.js
- views/librarian-login.hbs
- views/login.hbs
Bên trong không sử dụng layout nên phải tạo 1 trang include css bootstrap riêng.
> hoàn thành login cho thủ thư

- app.js
- public/stylesheets/lib-confirmID.css
- routes/lib-confirmID.js
- views/lib-confirmID.hbs
Chưa thể làm QR code scan vì chưa biết sẽ phối hợp với điện thoại hay máy quét thế nào. Cho nên làm tạm trang nhập tay.
> Confirm id for rent

- public/function/nav-lib.js
- views/borrow.hbs
- views/index-lib.hbs
- views/layout-lib.hbs
add <script src="/function/nav-lib.js" current_page=""></script> vào các trang chính tương ứng
điền attribute current_page = tên tương ứng của page
> change-nav-lib

- app.js
- routes/lib-profile.js
- views/lib-profile.hbs
Copy từ user sang thủ thư rồi sửa lại chút đỉnh. Chờ approve PR luật xong để đổi màu background
> Hoàn thành cơ bản trang profile

- README.md
- public/template-html/giaovien-dropdown.html
- public/template-html/sinhvien-dropdown.html
- views/change-password.hbs
- views/forget-pass.hbs
- views/profile.hbs
- views/sign-up.hbs
Như tiêu đề, chỉnh trong page change password, forget pass và profile. Ngoài ra chỉnh README liệt kê theo bullet
> Chỉnh sửa tiếng anh, giao diện change password và thêm href

- views/account-manager.hbs
- views/buy-book-manager.hbs
- views/lib-booking-book-manager.hbs
- views/post-announcer.hbs
Những trang này title font thin thay vì bold nên phải chỉnh lại.
> Chỉnh sửa 1 số title không đồng nhất

- views/account-manager.hbs
- views/buy-book-manager.hbs
- views/buy-book.hbs
- views/lib-booking-book-manager.hbs
GV: 
- trang quản lý mua sách
- trang đặt mua sách
Thủ thư:
- Quản lý account
- Quản lý sách đặt mua
> Chỉnh responsive lần 2

- public/function/csv.js
- routes/account-manager.js
- views/account-manager.hbs
- views/lib-booking-book-manager.hbs
2 export csv booking-manager and acc-manager
> Export csv

- public/function/slick-here.js
- public/stylesheets/forget-pass.css
- public/stylesheets/login.css
- public/stylesheets/sign-up.css
- public/stylesheets/style.css
- views/forget-pass.hbs
- views/login.hbs
- views/sign-up.hbs
Chỉnh tay font title resize theo media, sửa code nhưng giữ layout cũ. Đã test trên điện thoại thấy ok.
> Chỉnh sửa responsive trang login signup forget pass bể

- collections/buy-registed.js
- controllers/buy-registed.js
- controllers/comment.js
- routes/back-end/buy-registed.js
- services/buy-registed.js
> collection buy-registed

- controllers/bookDetail.js
- routes/front-end/book-detail.js
- routes/front-end/index.js
- services/account.js
- services/author.js
- services/book.js
- services/comment.js
- services/user.js
- views/book-detail.hbs
- views/index.hbs
Cũng đã chỉnh href ở trang chủ và phần sách liên quan. có thể click qua lại và load comment. 
Chưa có tính năng đăng comment / đánh giá
> Hoàn thành parse detail book

- controllers/bookDetail.js
- controllers/storage.js
- routes/front-end/storage.js
- services/book.js
- views/storage.hbs
> xong parse storage

- views/index.hbs
- views/login.hbs
- views/sign-up.hbs
Cũng như gán thêm id cho news ở trang chủ
> Đổi type password input trang đăng nhập và đăng kí

- controllers/LibLogin.js
- routes/front-end/lib-index.js
- routes/front-end/librarian-login.js
- views/layout-lib.hbs
- views/librarian-login.hbs
Khi vào trang lib thì sẽ check đã login chưa, nếu chưa thì chuyển sang trang login. nếu login (ở trang user) mà không phải acc admin thì cũng chuyển hướng.
> Hoàn thành lib login

- views/buy-book-manager.hbs
Sửa button Sửa width bằng hủy bỏ, và chỉnh padding hủy bỏ nhỏ lại.
> Chỉnh layout buy book manager

- views/layout.hbs
- views/news.hbs
Sửa lại thanh search trang news thành loại form.
> Hotfix: trang news chưa có tính năng search
